project_aggregator/app_users/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('reg/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('order/', OrderRegView.as_view(), name='registration_order'),
    path('account/', AccountView.as_view(), name='account'),
]

project_aggregator/project_aggregator/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('', include('app_products.urls')),
    path('api/', include('app_configurations.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('app_users.urls')),
    path('buy/', include('app_movement_goods.urls')),
    path('payment/', include('app_payments.urls')),
    # path('debug/', include('debug_toolbar.urls')),
    path('catalog/', include('app_filter_catalog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_aggregator/app_movement_goods/models.py
from decimal import Decimal

from django.conf import settings
from django.contrib import admin
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from app_products.models import Product


class UserCart(models.Model):
    owner = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='cart', verbose_name='Чья корзина', blank=True, null=True)
    session = models.CharField(
        verbose_name='Сессия', default='', max_length=40)
    cart = models.ManyToManyField(
        Product, through='InsideCart', verbose_name='Содержание корзины',
        related_name="carts", blank=True)

    def __str__(self):
        return 'Корзина ' + str(self.owner.email) if self.owner else 'Корзина Anonymous'

    def __len__(self):
        return sum(item.quantity for item in self.contents.only('quantity').all())

    def __iter__(self):
        for item in self.contents.all():
            data = {
                'total_price': item.cost * item.quantity,
                'product': item.product,
                'quantity': item.quantity,
                'price': item.cost,
            }
            yield data

    def add(self, product, quantity=1, update_quantity=False):
        cart = self.contents.get_or_create(user_cart=self, product=product)[0]
        if update_quantity:
            cart.quantity = quantity
        else:
            cart.quantity += quantity
        cart.cost = str(product.price)
        cart.save()

    def add_cart(self, cart):
        if cart:
            for goods in cart.contents.all():
                self.add(goods.product, goods.quantity)
            cart.clear()

    def remove(self, product):
        self.cart.remove(product)

    @property
    def get_total_price(self):
        return sum(
            Decimal(item.cost) * item.quantity for item in self.contents.only('quantity', 'cost').all())

    def clear(self):
        self.delete()

    class Meta:
        verbose_name = "Корзина пользователя"
        verbose_name_plural = "Корзины пользователей"


class InsideCart(models.Model):
    user_cart = models.ForeignKey(UserCart, on_delete=models.CASCADE, related_name='contents')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товары')
    quantity = models.PositiveSmallIntegerField(verbose_name='Количество', default=0)
    cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость', null=True)

    def __str__(self):
        return f'{self.product}={self.quantity} шт.'

    def save(self, *args, **kwargs):
        self.cost = str(self.product.price)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Order(models.Model):
    DELIVERY_CHOICES = (
        ("1", "Обычная доставка"),
        ("2", "Экспресс доставка"),)

    PAYMENT_CHOICES = (
        ("1", "Онлайн картой"),
        ("2", "Онлайн со случайного чужого счета"),)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Изменен')
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='order', on_delete=models.CASCADE, verbose_name='Чей заказ')
    city = models.CharField(max_length=100, verbose_name='Город')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    delivery_type = models.CharField(
        max_length=1, choices=DELIVERY_CHOICES, verbose_name='Тип доставки', default="1")
    payment_type = models.CharField(
        max_length=1, choices=PAYMENT_CHOICES, verbose_name='Тип оплаты', default="1")
    card_number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(10000000), MaxValueValidator(99999999)], verbose_name='Номер карты')
    delivery_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена доставки', default=0)
    paid = models.BooleanField(default=False, verbose_name='оплачен')
    status = models.CharField(max_length=150, verbose_name='Ошибки оплаты', blank=True, null=True)
    payment_code = models.IntegerField(default=0, verbose_name='Код оплаты')
    structure = models.ManyToManyField(
        Product, through='OrderContents', verbose_name='Содержание заказа', related_name='order')

    class Meta:
        ordering = ('-created_at',)
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f'Заказ {self.owner.email} №{self.id} от {self.created_at.strftime("%d-%m-%Y")}'

    @admin.display(description='Стоимость заказа')
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all()) + self.delivery_price


class OrderContents(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, verbose_name='товар')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='цена')
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.product}={self.quantity} шт.'

    def get_cost(self):
        return self.price * self.quantity

    def save(self, *args, **kwargs):
        self.price = str(self.product.price)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Содержание"
        verbose_name_plural = "Составы"

project_aggregator/app_users/models.py
from django.contrib import admin
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser, Group, PermissionsMixin
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, RegexValidator
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    image_validator = FileExtensionValidator(
        allowed_extensions=['png', 'jpg', 'gif'],
        message='Расширение не поддерживается. Разрешенные расширения .jpg .gif .png')

    def validate_size(self):
        filesize = self.file.size
        print(self.file.size)
        megabyte_limit = 2.0
        if filesize > megabyte_limit * 1024 * 1024:
            raise ValidationError("Максимальный размер файла %sMB" % str(megabyte_limit), code='invalid')

    phoneNumberValid = RegexValidator(regex=r"^\d{10}$")

    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    phone = models.CharField(unique=True, validators=[phoneNumberValid], max_length=10, verbose_name="Телефон")
    full_name = models.CharField(max_length=254, verbose_name='Полное имя', default='')
    avatar = models.ImageField(upload_to='avatars/', blank=True, verbose_name='Ссылка на изображение',
                               validators=[validate_size, image_validator])
    date_joined = models.DateTimeField(default=timezone.now, verbose_name='Дата регистрации')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    is_staff = models.BooleanField(default=False, verbose_name='Сотрудник')
    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.full_name

    @property
    def welcome_name(self):
        return ' '.join(self.full_name.split()[1:])

    @admin.display(description='Изображение')
    def get_image_avatar(self):
        if self.avatar:
            return mark_safe(f'<img src={self.avatar.url} height="50"')
        else:
            return 'Нет изображения'

    class Meta:
        ordering = ['id']
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class ProxyGroups(Group):
    class Meta:
        proxy = True
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

project_aggregator/app_users/forms.py
# from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from app_users.models import User

# User = get_user_model()


class RegUserForm(UserCreationForm):
    password1 = forms.CharField(
        max_length=150, required=True, widget=forms.PasswordInput(
            attrs={'class': 'form-input', 'data-validate': 'requirePassword',
                   'placeholder': 'Введите пароль', 'autocomplete': 'new-password',
                   'maxlength': '150'}))
    password2 = forms.CharField(
        max_length=150, required=True, widget=forms.PasswordInput(
            attrs={'class': 'form-input', 'data-validate': 'requireRepeatPassword',
                   'placeholder': 'Введите пароль повторно', 'autocomplete': 'new-password',
                   'maxlength': '150'}))
    full_name = forms.CharField(
        max_length=254, required=True, widget=forms.TextInput(
            attrs={'class': 'form-input', 'data-validate': 'require', 'placeholder': 'Введите Фамилию Имя Отчество',
                   'maxlength': '254'}))
    email = forms.EmailField(
        max_length=254, label='e-mail', required=True, widget=forms.TextInput(
            attrs={'class': 'form-input', 'data-validate': 'requireMail', 'maxlength': '254'}))
    phone = forms.CharField(
        required=True, widget=forms.TextInput(attrs={'class': 'form-input', 'data-validate': 'requirePhone'}))
    avatar = forms.ImageField(required=False, widget=forms.FileInput(
        attrs={'class': 'Profile-file form-input', 'type': "file",
               'accept': ".jpg,.gif,.png", 'data-validate': "onlyImgAvatar"}))

    class Meta:
        model = User
        fields = ('password1', 'password2', 'email', 'phone', 'avatar', 'full_name')

project_aggregator/app_users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import CreateView, UpdateView

from .forms import RegUserForm
from .models import User


class RegistrationView(CreateView):
    model = User
    form_class = RegUserForm
    template_name = 'app_users/registration.html'
    success_url = reverse_lazy('main')

    def post(self, request, *args, **kwargs):
        form = RegUserForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            my_group, result = Group.objects.get_or_create(name="Покупатели")
            my_group.user_set.add(user)
            login(request, user)
            return HttpResponseRedirect(self.success_url)
        return self.form_invalid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    raise_exception = True
    form_class = RegUserForm
    model = User
    template_name = 'app_users/profile.html'

    def get_success_url(self):
        return reverse('profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.info(self.request, "Профиль успешно сохранен")
        return super(ProfileView, self).form_valid(form)


class OrderRegView(RegistrationView):
    success_url = reverse_lazy('create_order')


class AccountView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'app_users/account.html'
    raise_exception = True

project_aggregator/app_users/templates/app_users/account.html
{% extends "base.html" %}
{% load static %}

{% block middle %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Личный кабинет
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{% url 'main' %}">домой</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>Личный кабинет</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">Навигация
                        </strong>
                    </header>
                    <div class="Section-columnContent">
                        <div class="NavigateProfile">
                            <ul class="menu menu_vt">
                                <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'account' %}">Личный
                                    кабинет</a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="{% url 'profile' %}">Профиль</a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="{% url 'history' %}">История заказов</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="Section-content">
                <div class="Account">
                    <div class="Account-group">
                        <div class="Account-column">
                            <div class="Account-avatar">
                                <img src="{% if request.user.avatar %} {{ request.user.avatar.url }} {% else %} {% static 'assets/img/content/home/empty_avatar.jpg' %} {% endif %}" alt="аватар"/>
                            </div>
                        </div>
                        <div class="Account-column">
                            <div class="Account-name">{{ request.user.full_name }}
                            </div>
                            <a class="Account-editLink" href="{% url 'profile' %}">Редактировать профиль</a>
                        </div>
                    </div>
                    {% if request.user.order.first %}
                    {% with order=request.user.order.first %}
                    <div class="Account-group">
                        <div class="Account-column Account-column_full">
                            <div class="Order Order_anons">
                                <div class="Order-personal">
                                    <div class="row">
                                        <div class="row-block"><a class="Order-title"
                                                                  href="{% url 'order_detail' order.id %}">Заказ&#32;<span
                                                class="Order-numberOrder">№{{ order.id }}</span>&#32;от&#32;<span
                                                class="Order-dateOrder">{{ order.created|date:"d.m.Y" }}</span></a>
                                            <div class="Account-editLink"><a href="{% url 'history' %}">История
                                                заказов</a>
                                            </div>
                                        </div>
                                        <div class="row-block">
                                            <div class="Order-info Order-info_delivery">
                                                <div class="Order-infoType">Тип доставки:
                                                </div>
                                                <div class="Order-infoContent">{{ order.get_delivery_type_display }}
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_pay">
                                                <div class="Order-infoType">Оплата:
                                                </div>
                                                <div class="Order-infoContent">{{ order.get_payment_type_display }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">Общая стоимость:
                                                </div>
                                                <div class="Order-infoContent">{{ order.get_total_cost }} <span class="code-rub">₽</span>
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_status">
                                                <div class="Order-infoType">Статус:
                                                </div>
                                                <div class="Order-infoContent">
                                             {% if order.paid %} <p style="color:#3cb878;">Оплачен</p>
                                             {% else %} <p style="color:#f26d7d;">Не оплачен</p> {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endwith %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

project_aggregator/app_users/templates/app_users/login_modal.html
{% load widget_tweaks %}

<form method="post" action="{% url 'login_modal' %}">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Вход</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span class="" aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="form-error {% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <div class="form-error">{{ error|escape }}</div>
          {% endfor %}
        </div>
      </div>
    {% endfor %}

    <!-- Hidden input field for custom redirection after successful login -->
    <input type="hidden" name="next" value="{{ success_url }}">
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary btn_success">Войти</button>
  </div>

</form>

<script>
      $(document).ready(function () {

          //email mask
          $('#id_email, #id_username').inputmask({
            mask: "*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,2}]",
            greedy: false,
            tabThrough:true,
            onBeforePaste: function (pastedValue, opts) {
              pastedValue = pastedValue.toLowerCase();
              return pastedValue.replace("mailto:", "");
            },
            definitions: {
              '*': {
                validator: "[0-9A-Za-z!#$%&'*+/=?^_`{|}~\-]",
                casing: "lower"
              }
            }
          });
      });
</script>

project_aggregator/app_users/templates/app_users/profile.html
{% extends "base.html" %}
{% load static %}
{% block middle %}
{% if user.avatar %}
{{ user.avatar.url|json_script:"user_avatar" }}
{% endif %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Профиль
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{% url 'main' %}">home</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>Профиль</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">Навигация
                        </strong>
                    </header>
                    <div class="Section-columnContent">
                        <div class="NavigateProfile">
                            <ul class="menu menu_vt">
                                <li class="menu-item"><a class="menu-link" href="{% url 'account' %}">Личный кабинет</a>
                                </li>
                                <li class="menu-item_ACTIVE menu-item"><a class="menu-link"
                                                                          href="{% url 'profile' %}">Профиль</a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="{% url 'history' %}">История заказов</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="Section-content">
                <div class="Profile">
                    <form class="form Profile-form" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                            <div class="form-error">{{ error|escape }}</div>
                            {% endfor %}
                        {% endif %}
                        <div class="row">
                            <div class="row-block">
                                <div class="form-group">
                                    <label class="form-label" for="{{ form.avatar.id_for_avatar }}">Аватар
                                    </label>
                                    <div class="Profile-avatar Profile-avatar_noimg">
                                        <div class="Profile-img">
                                            <img src="{%static 'assets/img/content/home/empty_avatar.jpg' %}" alt="аватар"/>
                                        </div>
                                        <label class="Profile-fileLabel" for="{{ form.avatar.id_for_avatar }}">Выберите
                                            аватар
                                        </label>
                                        {{ form.avatar }}
                                        {{ form.avatar.errors }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="form-label" for="{{ form.full_name.id_for_full_name }}">ФИО
                                    </label>
                                    {{ form.full_name }}
                                    {% if form.full_name.errors %}
                                        {% for error in form.full_name.errors %}
                                        <div class="form-error">{{ error|escape }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row-block">
                                <div class="form-group">
                                    <label class="form-label" for="{{ form.email.id_for_email }}">E-mail
                                    </label>
                                    {{ form.email }}
                                    {% if form.email.errors %}
                                        {% for error in form.email.errors %}
                                        <div class="form-error">{{ error|escape }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    <label class="form-label" for="{{ form.phone.id_for_phone }}">Телефон
                                    </label>
                                    {{ form.phone }}
                                    {% if form.phone.errors %}
                                        {% for error in form.phone.errors %}
                                        <div class="form-error">{{ error|escape }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    <label class="form-label" for="{{ form.password1.id_for_password1 }}">Пароль
                                    </label>
                                    {{ form.password1 }}
                                    {% if form.password1.errors %}
                                        {% for error in form.password1.errors %}
                                        <div class="form-error">{{ error|escape }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    <label class="form-label" for="{{ form.password2.id_for_password2 }}">Подтверждение
                                        пароля
                                    </label>
                                    {{ form.password2 }}
                                    {% if form.password2.errors %}
                                        {% for error in form.password2.errors %}
                                        <div class="form-error">{{ error|escape }}</div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    <div class="Profile-btn">
                                        <button class="btn btn_success" type="submit">Сохранить
                                        </button>
                                    </div>
                                    {% if messages %}
                                    {% for message in messages %}
                                        <div class="Profile-success">{{ message }}
                                        </div>
                                    {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}